version: "3.7"
services:
  cadfael:
    build: .
    depends_on:
      - db
    volumes:
      - ".:/app" #  Mount the local directory to the image so we don't have to restart our image to get new code
    env_file: .env
  db:
    image: mdillon/postgis:10
    ports:
      - "54321:5432"
    env_file: .env
